services:
  - type: static
    name: smartguard-frontend
    buildCommand: node build.js
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
