services:
  - type: static
    name: smartguard-frontend
    # Primary build command - npx approach (bypasses binary permission issues)
    buildCommand: npm install && npm run build
    # Alternative build commands (uncomment one if primary fails):
    # buildCommand: npm install && npx vite build
    # buildCommand: npm install && npm run render-build-yarn
    # buildCommand: node build.js
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
